# Building predictive models

In [1]:
import pandas as pd
import os
import numpy as np

## Import data

In [17]:
processed_data_path = os.path.join(os.path.pardir, "data", "processed").replace("\\","/")
train_file_path = os.path.join(processed_data_path, "train.csv").replace("\\","/")
test_file_path = os.path.join(processed_data_path, "test.csv").replace("\\","/")

..


In [25]:
train_df = pd.read_csv("C:/Users/z003t26s.AD001/Documents/doing_data_science_with_python/titanic/src/data/processed/train.csv", index_col="PassengerId")
test_df = pd.read_csv("C:/Users/z003t26s.AD001/Documents/doing_data_science_with_python/titanic/src/data/processed/test.csv", index_col="PassengerId")

In [26]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [27]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

## Data preparation

In [31]:
X = train_df.loc[:, "Age":].as_matrix().astype("float")
y = train_df["Survived"].ravel()

In [32]:
print X.shape, y.shape

(891L, 32L) (891L,)


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(712L, 32L) (712L,)
(179L, 32L) (179L,)


In [34]:
print "mean survival in train: {0: .3f}".format(np.mean(y_train))
print "mean survival in test: {0: .3f}".format(np.mean(y_test))

mean survival in train:  0.383
mean survival in test:  0.385


### check sci-kit learn version

In [35]:
import sklearn

In [36]:
sklearn.__version__

'0.19.1'

## Baseline model

In [38]:
from sklearn.dummy import DummyClassifier

In [39]:
model_dummy = DummyClassifier(strategy="most_frequent", random_state=0)

In [40]:
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [41]:
print "score for baseline model: {0: .2f}".format(model_dummy.score(X_test, y_test))

score for baseline model:  0.61


In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [43]:
print "accuracy for baseline model: {0: .2f}".format(accuracy_score(y_test, model_dummy.predict(X_test)))

accuracy for baseline model:  0.61


In [45]:
print "precision_score for baseline model: {0: .2f}".format(precision_score(y_test, model_dummy.predict(X_test)))
print "recall_score for baseline model: {0: .2f}".format(recall_score(y_test, model_dummy.predict(X_test)))

precision_score for baseline model:  0.00
recall_score for baseline model:  0.00


In [48]:
print "confusion_matrix for baseline model:\n {0}".format(confusion_matrix(y_test, model_dummy.predict(X_test)))

confusion_matrix for baseline model:
 [[110   0]
 [ 69   0]]


## First Kaggle Submission

In [49]:
def get_submission_file(model, filename):
    test_X = test_df.as_matrix().astype("float")
    predictions = model.predict(test_X)
    df_submission = pd.DataFrame({
        "PassengerId": test_df.index,
        "Survived": predictions
    })
    df_submission.to_csv(os.path.join("C:/Users/z003t26s.AD001/Documents/doing_data_science_with_python/titanic/src/data/external/", filename), index=False)

In [51]:
get_submission_file(model_dummy, "01_dummy.csv")

## Logistic Regression

In [52]:
from sklearn.linear_model import LogisticRegression

In [53]:
logistic_regression_model = LogisticRegression(random_state=0)

In [54]:
logistic_regression_model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [55]:
print "score for logistic regression model: {0: .2f}".format(logistic_regression_model.score(X_test, y_test))

score for logistic regression model:  0.83


In [56]:
print "accuracy for logistic_regression_model: {0: .2f}".format(accuracy_score(y_test, logistic_regression_model.predict(X_test)))
print "precision_score for logistic_regression_model: {0: .2f}".format(precision_score(y_test, logistic_regression_model.predict(X_test)))
print "recall_score for logistic_regression_model: {0: .2f}".format(recall_score(y_test, logistic_regression_model.predict(X_test)))
print "confusion_matrix for logistic_regression_model:\n {0}".format(confusion_matrix(y_test, logistic_regression_model.predict(X_test)))

accuracy for logistic_regression_model:  0.83
precision_score for logistic_regression_model:  0.78
recall_score for logistic_regression_model:  0.78
confusion_matrix for logistic_regression_model:
 [[95 15]
 [15 54]]


In [57]:
logistic_regression_model.coef_

array([[-0.02840733,  0.00455631, -0.5001701 ,  0.61922842, -0.81414743,
         0.12823264, -0.17253857, -0.39355489,  0.52215009,  1.09939126,
         0.40346551, -0.18369315, -0.30021028,  0.96558545,  0.4828179 ,
        -0.34516077,  0.28258589,  1.21850071,  0.5633418 , -1.44612509,
         1.07146231, -0.11345499, -0.47306806,  0.16297319,  0.24746355,
         0.27998259,  0.41282325,  0.49202888,  0.46214498,  0.14906871,
         0.37253568,  0.7307069 ]])

In [58]:
get_submission_file(logistic_regression_model, "2_logistic_regression_model.csv")

## Decision Trees

In [62]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)
acc_decision_tree

98.46

In [66]:
get_submission_file(decision_tree, "decision_tree_model.csv")

## Random Forest

In [65]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, y_train)
acc_random_forest = round(random_forest.score(X_train, y_train) * 100, 2)
acc_random_forest

98.46

In [67]:
get_submission_file(random_forest, "random_forest.csv")

## SVM

In [69]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_train, y_train) * 100, 2)
acc_svc

87.22

In [70]:
get_submission_file(svc, "svc.csv")

## K neighbors

In [72]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_train, y_train) * 100, 2)
acc_knn

83.85

In [73]:
get_submission_file(knn, "knn.csv")

## Hyperparameter optimization

In [74]:
model_lr = LogisticRegression(random_state=0)

In [75]:
from sklearn.model_selection import GridSearchCV

In [78]:
parameters = {
    "C": [1.0, 10.0, 50.0, 100.0, 1000.0], 
    "penalty": ["l1", "l2"]
}

clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [79]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [80]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [82]:
print "best score: {0: .2f}".format(clf.best_score_)

best score:  0.83


In [84]:
print "score for logistic regression: {0: .2f}".format(clf.score(X_test, y_test))

score for logistic regression:  0.83


In [85]:
get_submission_file(clf, "clf.csv")

### Feature normalization and standardization

#### Normalize

In [87]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [88]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [89]:
X_train_scaled[:,0].min(), X_train_scaled[:,0].max()

(0.0, 1.0)

In [90]:
X_test_scaled = scaler.transform(X_test)

#### standardization

In [91]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### create model after standardization

In [92]:
model_lr = LogisticRegression(random_state=0)
parameters = {
    "C": [1.0, 10.0, 50.0, 100.0, 1000.0], 
    "penalty": ["l1", "l2"]
}

clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [93]:
print "best score: {0: .2f}".format(clf.best_score_)

best score:  0.81


In [95]:
print "score for logistic regression: {0: .2f}".format(clf.score(X_test_scaled, y_test))

score for logistic regression:  0.84


## Model persistence

In [96]:
import pickle

In [100]:
model_file_path = os.path.join(os.getcwd(), "../models", "lr_model.pkl")
scaler_file_path = os.path.join(os.getcwd(), "../models", "lr_scaler.pkl")

In [101]:
model_file_pickle = open(model_file_path, "wb")
scaler_file_pickle = open(scaler_file_path, "wb")

In [102]:
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [103]:
model_file_pickle.close()
scaler_file_pickle.close()

#### load persisted file

In [105]:
model_file_pickle = open(model_file_path, "r")
scaler_file_pickle = open(scaler_file_path, "r")

clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)

model_file_pickle.close()
scaler_file_pickle.close()

In [106]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [107]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [108]:
X_test_scaled = scaler_loaded.transform(X_test)
print "score for persisted LR: {0: .2f}".format(clf_loaded.score(X_test_scaled, y_test))

score for persisted LR:  0.84
